# Generated by Django 6.0.5 on 2026-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='observacao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=12),
        ),
    ]
