# Generated by Django 6.0.5 on 2026-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_consulta_data_remove_consulta_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='triagem_justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='triagem_red_flags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
